class Autogenerated {
  List<Data>? data;
  Meta? meta;

  Autogenerated({this.data, this.meta});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
    meta = json['meta'] != null ? new Meta.fromJson(json['meta']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    if (this.meta != null) {
      data['meta'] = this.meta!.toJson();
    }
    return data;
  }
}

class Data {
  int? id;
  Attributes? attributes;

  Data({this.id, this.attributes});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    attributes = json['attributes'] != null
        ? new Attributes.fromJson(json['attributes'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    if (this.attributes != null) {
      data['attributes'] = this.attributes!.toJson();
    }
    return data;
  }
}

class Attributes {
  String? name;
  int? stars;
  String? price;
  String? oldprice;
  String? desc;
  String? brand;
  String? createdAt;
  String? updatedAt;
  String? thumb;
  String? secoundimg;
  String? thourdimg;
  int? quantity;
  Categories? categories;

  Attributes(
      {this.name,
      this.stars,
      this.price,
      this.oldprice,
      this.desc,
      this.brand,
      this.createdAt,
      this.updatedAt,
      this.thumb,
      this.secoundimg,
      this.thourdimg,
      this.quantity,
      this.categories});

  Attributes.fromJson(Map<String, dynamic> json) {
    name = json['attributes']['name'];
    stars = json['attributes']['stars'];
    price = json['attributes']['price'];
    oldprice = json['attributes']['oldprice'];
    desc = json['attributes']['desc'];
    brand = json['attributes']['brand'];
    createdAt = json['attributes']['createdAt'];
    updatedAt = json['attributes']['updatedAt'];
    thumb = json['attributes']['thumb'];
    secoundimg = json['attributes']['secoundimg'];
    thourdimg = json['attributes']['thourdimg'];
    quantity = json['attributes']['quantity'];
    categories = json['attributes']['categories'] != null
        ? new Categories.fromJson(json['attributes']['categories'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['attributes']['name'] = this.name;
    data['attributes']['stars'] = this.stars;
    data['attributes']['price'] = this.price;
    data['attributes']['oldprice'] = this.oldprice;
    data['attributes']['desc'] = this.desc;
    data['attributes']['brand'] = this.brand;
    data['attributes']['createdAt'] = this.createdAt;
    data['attributes']['updatedAt'] = this.updatedAt;
    data['attributes']['thumb'] = this.thumb;
    data['attributes']['secoundimg'] = this.secoundimg;
    data['attributes']['thourdimg'] = this.thourdimg;
    data['attributes']['quantity'] = this.quantity;
    if (this.categories != null) {
      data['attributes']['categories'] = this.categories!.toJson();
    }
    return data;
  }
}

class Categories {
  List<Data>? data;

  Categories({this.data});

  Categories.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class AttributesCreated {
  String? createdAt;
  String? updatedAt;
  String? name;

  AttributesCreated({this.createdAt, this.updatedAt, this.name});

  AttributesCreated.fromJson(Map<String, dynamic> json) {
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    data['name'] = this.name;
    return data;
  }
}

class Meta {
  Pagination? pagination;

  Meta({this.pagination});

  Meta.fromJson(Map<String, dynamic> json) {
    pagination = json['pagination'] != null
        ? new Pagination.fromJson(json['pagination'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.pagination != null) {
      data['pagination'] = this.pagination!.toJson();
    }
    return data;
  }
}

class Pagination {
  int? page;
  int? pageSize;
  int? pageCount;
  int? total;

  Pagination({this.page, this.pageSize, this.pageCount, this.total});

  Pagination.fromJson(Map<String, dynamic> json) {
    page = json['page'];
    pageSize = json['pageSize'];
    pageCount = json['pageCount'];
    total = json['total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['page'] = this.page;
    data['pageSize'] = this.pageSize;
    data['pageCount'] = this.pageCount;
    data['total'] = this.total;
    return data;
  }
}
