// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT16tMXq46omVX-E8L_XvElpj83HaCNe8',
    appId: '1:1083652639685:web:f9a77914554ee0ba5719ac',
    messagingSenderId: '1083652639685',
    projectId: 'storyes',
    authDomain: 'storyes.firebaseapp.com',
    storageBucket: 'storyes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwYidUorO7mM1435YHNDCfVQD2lAZptK8',
    appId: '1:1083652639685:android:71ac5d5951d132755719ac',
    messagingSenderId: '1083652639685',
    projectId: 'storyes',
    storageBucket: 'storyes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKvuHjinWVRSgFc5rf3kXzAVAuv_R0xC8',
    appId: '1:1083652639685:ios:25d1fc91856506b25719ac',
    messagingSenderId: '1083652639685',
    projectId: 'storyes',
    storageBucket: 'storyes.appspot.com',
    iosClientId: '1083652639685-3pr87b0s4pg8c7or7iiiqns18hlovmom.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttercode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKvuHjinWVRSgFc5rf3kXzAVAuv_R0xC8',
    appId: '1:1083652639685:ios:25d1fc91856506b25719ac',
    messagingSenderId: '1083652639685',
    projectId: 'storyes',
    storageBucket: 'storyes.appspot.com',
    iosClientId: '1083652639685-3pr87b0s4pg8c7or7iiiqns18hlovmom.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttercode',
  );
}
